### ISSUE TITLE
Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by musasutisna** [musasutisna/mikro-cms#1]
Something error after installation and access home page

TypeError: Cannot read property 'status' of undefined
    at Object.serviceResourceGenerate (/home/node/app/node_modules/@mikro-cms/core/generate.js:34:25)
    at apiExecute (/home/node/app/node_modules/@mikro-cms/core/express.js:112:35)
    at Object.defaultData (/home/node/app/node_modules/@mikro-cms/theme-web-stories/index.js:11:22)
    at /home/node/app/node_modules/@mikro-cms/core/generate.js:74:38
    at /home/node/app/node_modules/mongoose/lib/model.js:5074:18
    at processTicksAndRejections (node:internal/process/task_queues:76:11)

**Comment by musasutisna** [comment]
This error produces when theme data accessing api resource
Every api resource must have middleware serviceResourceGenerate as the latest handler and that don't call by apiExecute
In this case, that middleware is not the latest handler so will be called on apiExecute
Check api resource used by theme data if there have multiple resource with the same api path you must remove that
